### ISSUE TITLE
GPIO_NUM used in stead of define "sda"

### ISSUE THREAD

**Issue by basaandewiel** [technosf/ESP32-Peripheral-Drivers#1]
sorry, I don't have any experience with github.
I have TTGO T-camera; 
I had to change line 58 as follows:
    pif = new I2C_PIF{scl, sda, 0x3c}; //BUG:GPIO_NUM_18 replaced by sda

Because T-camera uses other SDA and SCL pins.

**Comment by technosf** [comment]
Not an issue.
